//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.24 at 05:13:27 PM EDT 
//
package com.tntdjs.soloplayer.data.config.objects;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "playlist" })
@XmlRootElement(name = "PlayLists")
public class ListPlayLists {

	protected List<Playlist> playlist;
	@XmlAttribute(name = "dtype")
	protected String dtype;

	/**
	 * Gets the value of the playlist property. This accessor method returns a
	 * reference to the live list, not a snapshot. Therefore any modification
	 * you make to the returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the playlist
	 * property.
	 */
	public List<Playlist> getPlaylist() {
		if (playlist == null) {
			playlist = new ArrayList<Playlist>();
		}

		Collections.sort(playlist, new Comparator<Playlist>() {
			@Override
			public int compare(Playlist playlist1, Playlist playlist2) {
				// -1 - less than, 1 - greater than, 0 - equal, all inversed for descending		
				return playlist2.getPlId() > playlist1.getPlId() ? -1 : (playlist2.getPlId() < playlist1.getPlId() ) ? 1 : 0;
			}
        });
		
		return this.playlist;
	}

	/**
	 * Gets the value of the dtype property.
	 */
	public String getDtype() {
		return dtype;
	}

	/**
	 * Sets the value of the dtype property.
	 */
	public void setDtype(String value) {
		this.dtype = value;
	}
}
